#ifndef _T2KRW_BUILD_INFO_H_ 
#define _T2KRW_BUILD_INFO_H_ 
/* 
 * Build information automatically generated by the T2KReWeight installer 
*/ 

#define __T2KRW_OAANALYSIS_ENABLED__
//#define __T2KRW_GENIE_ENABLED__
#define __T2KRW_NEUT_ENABLED__
//#define __T2KRW_JNUBEAM_ENABLED__
#define __T2KRW_NIWG_ENABLED__
//#define __T2KRW_GEANT_ENABLED__
//#define __T2KRW_TRACKERFILE_ENABLED__
#define __T2KRW_PSYCHE_ENABLED__

#endif

