#ifndef _T2KRW_VERSION_H_ 
#define _T2KRW_VERSION_H_ 
/* 
 * Version information automatically generated by the T2KReWeight installer 
 * 
 * These macros can be used in the following way (as the ones at ROOT's RVersion.h): 
 * #if __T2KREWEIGHT_RELEASE_CODE__ >= T2KREWEIGHTRELCODE(2,4,11) 
 * #include <newheader.h>
 * #else
 * #include <oldheader.h>
 * #endif
*/ 

#define T2KREWEIGHTRELCODE(a,b,c) (((a) << 16) + ((b) << 8) + (c)) 

#define __T2KREWEIGHT_RELEASE__      "1.27"
#define __T2KREWEIGHT_RELEASE_CODE__ T2KREWEIGHTRELCODE(,,) 

#endif

