//
// File generated by /physics/software/t2k/ND280/v11r31/ROOT/v5r34p09n04/Linux-x86_64/bin/rootcint at Mon Oct  9 06:39:30 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIdictdIControlPanel_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ControlPanel_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ctrlcLcLControlPanel_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_ctrlcLcLControlPanel(void *p);
   static void deleteArray_ctrlcLcLControlPanel(void *p);
   static void destruct_ctrlcLcLControlPanel(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ctrl::ControlPanel*)
   {
      ::ctrl::ControlPanel *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ctrl::ControlPanel >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ctrl::ControlPanel", ::ctrl::ControlPanel::Class_Version(), "./../src/EventDisplay/ControlPanel.hxx", 20,
                  typeid(::ctrl::ControlPanel), DefineBehavior(ptr, ptr),
                  &::ctrl::ControlPanel::Dictionary, isa_proxy, 4,
                  sizeof(::ctrl::ControlPanel) );
      instance.SetDelete(&delete_ctrlcLcLControlPanel);
      instance.SetDeleteArray(&deleteArray_ctrlcLcLControlPanel);
      instance.SetDestructor(&destruct_ctrlcLcLControlPanel);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ctrl::ControlPanel*)
   {
      return GenerateInitInstanceLocal((::ctrl::ControlPanel*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ctrl::ControlPanel*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace ctrl {
//______________________________________________________________________________
TClass *ControlPanel::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ControlPanel::Class_Name()
{
   return "ctrl::ControlPanel";
}

//______________________________________________________________________________
const char *ControlPanel::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ctrl::ControlPanel*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ControlPanel::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ctrl::ControlPanel*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ControlPanel::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ctrl::ControlPanel*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ControlPanel::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ctrl::ControlPanel*)0x0)->GetClass();
   return fgIsA;
}

} // namespace ctrl
      namespace ctrl {
//______________________________________________________________________________
void ControlPanel::Streamer(TBuffer &R__b)
{
   // Stream an object of class ctrl::ControlPanel.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ctrl::ControlPanel::Class(),this);
   } else {
      R__b.WriteClassBuffer(ctrl::ControlPanel::Class(),this);
   }
}

} // namespace ctrl
//______________________________________________________________________________
      namespace ctrl {
void ControlPanel::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ctrl::ControlPanel.
      TClass *R__cl = ::ctrl::ControlPanel::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_plotEvent", &_plotEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_readEvent", &_readEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_button_neutral", &_button_neutral);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_spill_number", &_spill_number);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_canvas_control[3]", &_canvas_control);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_obj_control[2]", &_obj_control);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_cnv_group", &_cnv_group);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_obj_group", &_obj_group);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_canvas_main", &_canvas_main);
      TGMainFrame::ShowMembers(R__insp);
}

} // namespace ctrl
namespace ROOT {
   // Wrapper around operator delete
   static void delete_ctrlcLcLControlPanel(void *p) {
      delete ((::ctrl::ControlPanel*)p);
   }
   static void deleteArray_ctrlcLcLControlPanel(void *p) {
      delete [] ((::ctrl::ControlPanel*)p);
   }
   static void destruct_ctrlcLcLControlPanel(void *p) {
      typedef ::ctrl::ControlPanel current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ctrl::ControlPanel

/********************************************************
* ../dict/ControlPanel_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableControlPanel_Dict();

extern "C" void G__set_cpp_environmentControlPanel_Dict() {
  G__cpp_reset_tagtableControlPanel_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevControlPanel_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ctrl::ControlPanel */
static int G__ControlPanel_Dict_1034_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ctrl::ControlPanel* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ctrl::ControlPanel(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) ctrl::ControlPanel(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((ctrl::ControlPanel*) G__getstructoffset())->Initialize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((ctrl::ControlPanel*) G__getstructoffset())->InitializeBase());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((ctrl::ControlPanel*) G__getstructoffset())->GetReadyStatus());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetEventPlotter((plot::EventPlotter*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDetForager((det::DetectorForager*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetEventReader((evrd::EventReader*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->GetSpill();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDrawXZCanvas((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDrawYZCanvas((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDrawXYCanvas((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDrawTrueParticles((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->SetDrawRecoParticles((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ctrl::ControlPanel::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ctrl::ControlPanel::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ctrl::ControlPanel::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ctrl::ControlPanel::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ctrl::ControlPanel*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ctrl::ControlPanel::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ctrl::ControlPanel::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ctrl::ControlPanel::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ControlPanel_Dict_1034_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ctrl::ControlPanel::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ctrl::ControlPanel G__TctrlcLcLControlPanel;
static int G__ControlPanel_Dict_1034_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ctrl::ControlPanel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ctrl::ControlPanel*) (soff+(sizeof(ctrl::ControlPanel)*i)))->~G__TctrlcLcLControlPanel();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ctrl::ControlPanel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ctrl::ControlPanel*) (soff))->~G__TctrlcLcLControlPanel();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ctrl::ControlPanel */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncControlPanel_Dict {
 public:
  G__Sizep2memfuncControlPanel_Dict(): p(&G__Sizep2memfuncControlPanel_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncControlPanel_Dict::*p)();
};

size_t G__get_sizep2memfuncControlPanel_Dict()
{
  G__Sizep2memfuncControlPanel_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceControlPanel_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel))) {
     ctrl::ControlPanel *G__Lderived;
     G__Lderived=(ctrl::ControlPanel*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),G__get_linked_tagnum(&G__ControlPanel_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableControlPanel_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*,less<long> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,Int_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,DetBBox>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,pair<TVector3,TVector3> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,pair<TVector3,TVector3>,less<int> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,PlotAttLine>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,datt::PlotAttLine>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,datt::PlotAttLine,less<int> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaBunchC*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaTrueParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaDetCrossingB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaTPCParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaFGDParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaECALParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaSMRDParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaP0DParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaParticleB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<AnaTrueVertexB*,AnaRecTrueMatchB> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<AnaTrueVertexB*,AnaRecTrueMatchB> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<AnaTrueVertexB*,AnaRecTrueMatchB> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaVertexB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaTrueVertexB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaFgdTimeBinB*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TBox*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETBoxmUcOallocatorlETBoxmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETBoxmUcOallocatorlETBoxmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVector3>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TObject*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TChain*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*,less<string> >",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<InputConverter*>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ctrl::ControlPanel */
static void G__setup_memvarctrlcLcLControlPanel(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel));
   { ctrl::ControlPanel *p; p=(ctrl::ControlPanel*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kDraw=57LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kNeutral=58LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kXZ=59LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kYZ=60LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kXY=61LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kTrue=62LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kReco=63LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kNextBunch=64LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kBackBunch=65LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kNextSpill=66LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kBackSpill=67LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kGoToSpill=68LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA),-1,-2,2,"kQuit=69LL",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_plotcLcLEventPlotter),-1,-1,2,"_plotEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_evrdcLcLEventReader),-1,-1,2,"_readEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGCheckButton),-1,-1,2,"_button_neutral=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGNumberEntry),-1,-1,2,"_spill_number=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGCheckButton),-1,-1,2,"_canvas_control[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGCheckButton),-1,-1,2,"_obj_control[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGButtonGroup),-1,-1,2,"_cnv_group=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TGButtonGroup),-1,-1,2,"_obj_group=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TRootEmbeddedCanvas),-1,-1,2,"_canvas_main=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ControlPanel_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarControlPanel_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncctrlcLcLControlPanel(void) {
   /* ctrl::ControlPanel */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel));
   G__memfunc_setup("ControlPanel",1233,G__ControlPanel_Dict_1034_0_1, 105, G__get_linked_tagnum(&G__ControlPanel_DictLN_ctrlcLcLControlPanel), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__ControlPanel_Dict_1034_0_2, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitializeBase",1421,G__ControlPanel_Dict_1034_0_3, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetReadyStatus",1433,G__ControlPanel_Dict_1034_0_4, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventPlotter",1560,G__ControlPanel_Dict_1034_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'plot::EventPlotter' - 0 - plot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDetForager",1295,G__ControlPanel_Dict_1034_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "U 'det::DetectorForager' - 0 - dfor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventReader",1409,G__ControlPanel_Dict_1034_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "U 'evrd::EventReader' - 0 - read", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSpill",804,G__ControlPanel_Dict_1034_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawXZCanvas",1480,G__ControlPanel_Dict_1034_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawYZCanvas",1481,G__ControlPanel_Dict_1034_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawXYCanvas",1479,G__ControlPanel_Dict_1034_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawTrueParticles",2049,G__ControlPanel_Dict_1034_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawRecoParticles",2026,G__ControlPanel_Dict_1034_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessMessage",1444,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 2, 0, 
"l - 'Long_t' 0 - msg l - 'Long_t' 0 - parm1 "
"l - 'Long_t' 0 - parm2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("QuitProgram",1147,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawEvent",912,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeBunch",1078,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "g - - 0 - forward", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFwdSpill",1093,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBwdSpill",1089,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawNeutral",1429,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "g - - 0 - draw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ControlPanel_Dict_1034_0_21, 85, G__get_linked_tagnum(&G__ControlPanel_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ctrl::ControlPanel::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ControlPanel_Dict_1034_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ctrl::ControlPanel::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ControlPanel_Dict_1034_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ctrl::ControlPanel::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ControlPanel_Dict_1034_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ctrl::ControlPanel::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ControlPanel_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ControlPanel_Dict_1034_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ControlPanel_Dict_1034_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ctrl::ControlPanel::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ControlPanel_Dict_1034_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ctrl::ControlPanel::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ControlPanel_Dict_1034_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ctrl::ControlPanel::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ControlPanel_Dict_1034_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ctrl::ControlPanel::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~ControlPanel", 1359, G__ControlPanel_Dict_1034_0_33, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncControlPanel_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalControlPanel_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcControlPanel_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ControlPanel_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGButtonGroup = { "TGButtonGroup" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR = { "map<long,int,less<long>,allocator<pair<const long,int> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR = { "map<long,TGeoNavigatorArray*,less<long>,allocator<pair<const long,TGeoNavigatorArray*> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_det = { "det" , 110 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_detcLcLDetectorForager = { "det::DetectorForager" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR = { "map<int,pair<TVector3,TVector3>,less<int>,allocator<pair<const int,pair<TVector3,TVector3> > > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR = { "map<int,datt::PlotAttLine,less<int>,allocator<pair<const int,datt::PlotAttLine> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR = { "vector<AnaBunchC*,allocator<AnaBunchC*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaBunchC*,allocator<AnaBunchC*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR = { "vector<AnaTrueParticleB*,allocator<AnaTrueParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaTrueParticleB*,allocator<AnaTrueParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR = { "vector<AnaDetCrossingB*,allocator<AnaDetCrossingB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaDetCrossingB*,allocator<AnaDetCrossingB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR = { "vector<AnaTPCParticleB*,allocator<AnaTPCParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaTPCParticleB*,allocator<AnaTPCParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR = { "vector<AnaFGDParticleB*,allocator<AnaFGDParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaFGDParticleB*,allocator<AnaFGDParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR = { "vector<AnaECALParticleB*,allocator<AnaECALParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaECALParticleB*,allocator<AnaECALParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR = { "vector<AnaSMRDParticleB*,allocator<AnaSMRDParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaSMRDParticleB*,allocator<AnaSMRDParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR = { "vector<AnaP0DParticleB*,allocator<AnaP0DParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaP0DParticleB*,allocator<AnaP0DParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR = { "vector<AnaParticleB*,allocator<AnaParticleB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaParticleB*,allocator<AnaParticleB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR = { "vector<pair<AnaTrueVertexB*,AnaRecTrueMatchB>,allocator<pair<AnaTrueVertexB*,AnaRecTrueMatchB> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<AnaTrueVertexB*,AnaRecTrueMatchB>,allocator<pair<AnaTrueVertexB*,AnaRecTrueMatchB> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR = { "vector<AnaVertexB*,allocator<AnaVertexB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaVertexB*,allocator<AnaVertexB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR = { "vector<AnaTrueVertexB*,allocator<AnaTrueVertexB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaTrueVertexB*,allocator<AnaTrueVertexB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR = { "vector<AnaFgdTimeBinB*,allocator<AnaFgdTimeBinB*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaFgdTimeBinB*,allocator<AnaFgdTimeBinB*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_plot = { "plot" , 110 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR = { "vector<TBox*,allocator<TBox*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlETBoxmUcOallocatorlETBoxmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TBox*,allocator<TBox*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_plotcLcLEventPlotter = { "plot::EventPlotter" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR = { "vector<TVector3,allocator<TVector3> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVector3,allocator<TVector3> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR = { "vector<TObject*,allocator<TObject*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TObject*,allocator<TObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR = { "map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR = { "vector<InputConverter*,allocator<InputConverter*> >" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_reverse_iteratorlEvectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<InputConverter*,allocator<InputConverter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_evrd = { "evrd" , 110 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_evrdcLcLEventReader = { "evrd::EventReader" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_ctrl = { "ctrl" , 110 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_ctrlcLcLControlPanel = { "ctrl::ControlPanel" , 99 , -1 };
G__linked_taginfo G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA = { "ctrl::ControlPanel::$" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableControlPanel_Dict() {
  G__ControlPanel_DictLN_TClass.tagnum = -1 ;
  G__ControlPanel_DictLN_TBuffer.tagnum = -1 ;
  G__ControlPanel_DictLN_TMemberInspector.tagnum = -1 ;
  G__ControlPanel_DictLN_TObject.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TGObject.tagnum = -1 ;
  G__ControlPanel_DictLN_TQObject.tagnum = -1 ;
  G__ControlPanel_DictLN_TGWindow.tagnum = -1 ;
  G__ControlPanel_DictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TGFrame.tagnum = -1 ;
  G__ControlPanel_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__ControlPanel_DictLN_TGMainFrame.tagnum = -1 ;
  G__ControlPanel_DictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__ControlPanel_DictLN_TGButtonGroup.tagnum = -1 ;
  G__ControlPanel_DictLN_TGCheckButton.tagnum = -1 ;
  G__ControlPanel_DictLN_TGNumberEntry.tagnum = -1 ;
  G__ControlPanel_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__ControlPanel_DictLN_det.tagnum = -1 ;
  G__ControlPanel_DictLN_detcLcLDetectorForager.tagnum = -1 ;
  G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_plot.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlETBoxmUcOallocatorlETBoxmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_plotcLcLEventPlotter.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR.tagnum = -1 ;
  G__ControlPanel_DictLN_reverse_iteratorlEvectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ControlPanel_DictLN_evrd.tagnum = -1 ;
  G__ControlPanel_DictLN_evrdcLcLEventReader.tagnum = -1 ;
  G__ControlPanel_DictLN_ctrl.tagnum = -1 ;
  G__ControlPanel_DictLN_ctrlcLcLControlPanel.tagnum = -1 ;
  G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableControlPanel_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGButtonGroup);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_det);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_detcLcLDetectorForager);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplEintcOpairlETVector3cOTVector3gRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlETVector3cOTVector3gRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplEintcOdattcLcLPlotAttLinecOlesslEintgRcOallocatorlEpairlEconstsPintcOdattcLcLPlotAttLinegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueParticleBmUcOallocatorlEAnaTrueParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaDetCrossingBmUcOallocatorlEAnaDetCrossingBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTPCParticleBmUcOallocatorlEAnaTPCParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFGDParticleBmUcOallocatorlEAnaFGDParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaECALParticleBmUcOallocatorlEAnaECALParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaSMRDParticleBmUcOallocatorlEAnaSMRDParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaP0DParticleBmUcOallocatorlEAnaP0DParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaParticleBmUcOallocatorlEAnaParticleBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRcOallocatorlEpairlEAnaTrueVertexBmUcOAnaRecTrueMatchBgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaVertexBmUcOallocatorlEAnaVertexBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaTrueVertexBmUcOallocatorlEAnaTrueVertexBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEAnaFgdTimeBinBmUcOallocatorlEAnaFgdTimeBinBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_plot);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlETBoxmUcOallocatorlETBoxmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETBoxmUcOallocatorlETBoxmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_plotcLcLEventPlotter);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlETVector3cOallocatorlETVector3gRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_vectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_reverse_iteratorlEvectorlEInputConvertermUcOallocatorlEInputConvertermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_evrd);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_evrdcLcLEventReader);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_ctrl);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_ctrlcLcLControlPanel),sizeof(ctrl::ControlPanel),-1,324608,(char*)NULL,G__setup_memvarctrlcLcLControlPanel,G__setup_memfuncctrlcLcLControlPanel);
   G__get_linked_tagnum_fwd(&G__ControlPanel_DictLN_ctrlcLcLControlPanelcLcLdA);
}
extern "C" void G__cpp_setupControlPanel_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupControlPanel_Dict()");
  G__set_cpp_environmentControlPanel_Dict();
  G__cpp_setup_tagtableControlPanel_Dict();

  G__cpp_setup_inheritanceControlPanel_Dict();

  G__cpp_setup_typetableControlPanel_Dict();

  G__cpp_setup_memvarControlPanel_Dict();

  G__cpp_setup_memfuncControlPanel_Dict();
  G__cpp_setup_globalControlPanel_Dict();
  G__cpp_setup_funcControlPanel_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncControlPanel_Dict();
  return;
}
class G__cpp_setup_initControlPanel_Dict {
  public:
    G__cpp_setup_initControlPanel_Dict() { G__add_setup_func("ControlPanel_Dict",(G__incsetup)(&G__cpp_setupControlPanel_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initControlPanel_Dict() { G__remove_setup_func("ControlPanel_Dict"); }
};
G__cpp_setup_initControlPanel_Dict G__cpp_setup_initializerControlPanel_Dict;

