/* Version information autogenerated by version fragment */
#ifndef BANFF_NAME
#define BANFF_NAME "BANFF"
#define BANFF_VERSION "v3r16"
#define BANFF_MAJOR_VERSION 3
#define BANFF_MINOR_VERSION 16
#define BANFF_PATCH_VERSION 0
#define BEFORE_BANFF(v,r,p) ((BANFF_MAJOR_VERSION==(v)&&BANFF_MINOR_VERSION==(r)&&BANFF_PATCH_VERSION<(p))||(BANFF_MAJOR_VERSION==(v)&&BANFF_MINOR_VERSION<(r))||(BANFF_MAJOR_VERSION<(v)))
#define EQUALS_BANFF(v,r,p) (BANFF_MAJOR_VERSION==(v)&&BANFF_MINOR_VERSION==(r)&&BANFF_PATCH_VERSION==(p))
#define BANFF_COMPILE_DATE "Wed Oct 4 18:22:02 UTC 2017"
#define BANFF_COMPILE_HOST "ens-hpc"
#define BANFF_COMPILE_UNAME "Linux ens-hpc 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
#define BANFF_COMPILE_DIR "/physics/home/mhogan/software/t2k-software-clone/BANFF/v3r16/cmt"
#endif
