//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:21 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TDataVector_h
#define ND__TDataVector_h
namespace ND {
class TDataVector;
} // end of namespace.

#include "ND__TData.h"
#include "Riostream.h"
#include <vector>
#include "ND__TDatum.h"

namespace ND {
class TDataVector : public ND::TData {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<ND::TDatum*> fVector;     //

   TDataVector();
   TDataVector(const TDataVector & );
   virtual ~TDataVector();

   ClassDef(TDataVector,5); // Generated by MakeProject.
};
} // namespace
#endif
