//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisHeaderModuleBase_h
#define ND__TAnalysisHeaderModuleBase_h
namespace ND {
class TAnalysisHeaderModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisHeaderModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisHeaderModuleBase();
   TAnalysisHeaderModuleBase(const TAnalysisHeaderModuleBase & );
   virtual ~TAnalysisHeaderModuleBase();

   ClassDef(TAnalysisHeaderModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
