//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrueVertex_h
#define ND__TTrueVertex_h
namespace ND {
class TTrueVertex;
} // end of namespace.

#include "TObject.h"
#include "TLorentzVector.h"

namespace ND {
class TTrueVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   Int_t          ID;          //
   double         Pur;         //
   double         Eff;         //

   TTrueVertex();
   TTrueVertex(const TTrueVertex & );
   virtual ~TTrueVertex();

   ClassDef(TTrueVertex,2); // Generated by MakeProject.
};
} // namespace
#endif
