//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TRooTrackerVtxModuleBase_h
#define ND__TRooTrackerVtxModuleBase_h
namespace ND {
class TRooTrackerVtxModuleBase;
} // end of namespace.

#include "ND__TAnalysisTruthModuleBase.h"
#include "TClonesArray.h"

namespace ND {
class TRooTrackerVtxModuleBase : public ND::TAnalysisTruthModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       fNVtx;       ///< The number of vertices
   TClonesArray* fVtx;        ///< TClonesArray of vertex objects 
   bool          fPassThroughPresent;    //

   TRooTrackerVtxModuleBase();
   TRooTrackerVtxModuleBase(const TRooTrackerVtxModuleBase & );
   virtual ~TRooTrackerVtxModuleBase();

   ClassDef(TRooTrackerVtxModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
