//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TExample2010aAnalysis1Module_h
#define ND__TExample2010aAnalysis1Module_h
namespace ND {
class TExample2010aAnalysis1Module;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TExample2010aAnalysis1Module : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Double_t    fTimeOffset;    //

   TExample2010aAnalysis1Module();
   TExample2010aAnalysis1Module(const TExample2010aAnalysis1Module & );
   virtual ~TExample2010aAnalysis1Module();

   ClassDef(TExample2010aAnalysis1Module,2); // Generated by MakeProject.
};
} // namespace
#endif
