//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisModuleBase_h
#define ND__TAnalysisModuleBase_h
namespace ND {
class TAnalysisModuleBase;
} // end of namespace.

#include "TNamed.h"
#include "TTree.h"
#include "Riostream.h"
#include <string>

namespace ND {
class TAnalysisModuleBase : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   Bool_t      fIsEnabled;    //
   Bool_t      fIsUsedForPreselection;    //
   TTree*      fOutputTree;               //
   Int_t       fBufferSize;               //Buffer Size for TBranch.
   Int_t       fSplitLevel;               ///< Split Level for TBranch.
   string      fDescription;              ///< A longish descrition of the analysis
   string      fCVSTagName;               ///< Defined if an official tagged version
   string      fCVSID;                    ///< Defined if an official tagged version
   Int_t       fRunID;                    //
   Int_t       fSubrunID;                 //
   Int_t       fEventID;                  //
   Int_t       fPreselected;              //
   string      fInputDirectory;           ///< An input directory where analysis modules can search for extra files.

   TAnalysisModuleBase();
   TAnalysisModuleBase(const TAnalysisModuleBase & );
   virtual ~TAnalysisModuleBase();

   ClassDef(TAnalysisModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
