//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TBasicDataQualityModule_h
#define ND__TBasicDataQualityModule_h
namespace ND {
class TBasicDataQualityModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"

namespace ND {
class TBasicDataQualityModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TBasicDataQualityModule();
   TBasicDataQualityModule(const TBasicDataQualityModule & );
   virtual ~TBasicDataQualityModule();

   ClassDef(TBasicDataQualityModule,2); // Generated by MakeProject.
};
} // namespace
#endif
