//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 27 21:29:22 2017 by ROOT version 5.34/09)
//      from the StreamerInfo in file /physics/data/MC_Productions/GRID/mcp6_Spin_B/neut/run4-water/anal/oa_nt_beam_90410000-0023_wjojmfzpy6p4_anal_001_prod6amagnet201011waterc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGRooTrackerVtxModule_h
#define ND__TGRooTrackerVtxModule_h
namespace ND {
class TGRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TGRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TGRooTrackerVtxModule();
   TGRooTrackerVtxModule(const TGRooTrackerVtxModule & );
   virtual ~TGRooTrackerVtxModule();

   ClassDef(TGRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
