/********************************************************************
* dict/Headerdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/Headerdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHeaderdict();
extern void G__cpp_setup_inheritanceHeaderdict();
extern void G__cpp_setup_typetableHeaderdict();
extern void G__cpp_setup_memvarHeaderdict();
extern void G__cpp_setup_globalHeaderdict();
extern void G__cpp_setup_memfuncHeaderdict();
extern void G__cpp_setup_funcHeaderdict();
extern void G__set_cpp_environmentHeaderdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/Header.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HeaderdictLN_TClass;
extern G__linked_taginfo G__HeaderdictLN_TBuffer;
extern G__linked_taginfo G__HeaderdictLN_TMemberInspector;
extern G__linked_taginfo G__HeaderdictLN_TObject;
extern G__linked_taginfo G__HeaderdictLN_string;
extern G__linked_taginfo G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HeaderdictLN_TTree;
extern G__linked_taginfo G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__HeaderdictLN_Header;

/* STUB derived class for protected member access */
