//
// File generated by /physics/software/t2k/ND280/v11r31/ROOT/v5r34p09n04/Linux-x86_64/bin/rootcint at Mon Dec 18 14:31:27 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictdIHeaderdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Headerdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Header_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Header(void *p = 0);
   static void *newArray_Header(Long_t size, void *p);
   static void delete_Header(void *p);
   static void deleteArray_Header(void *p);
   static void destruct_Header(void *p);
   static void streamer_Header(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Header*)
   {
      ::Header *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Header >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Header", ::Header::Class_Version(), "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/Header.hxx", 10,
                  typeid(::Header), DefineBehavior(ptr, ptr),
                  &::Header::Dictionary, isa_proxy, 0,
                  sizeof(::Header) );
      instance.SetNew(&new_Header);
      instance.SetNewArray(&newArray_Header);
      instance.SetDelete(&delete_Header);
      instance.SetDeleteArray(&deleteArray_Header);
      instance.SetDestructor(&destruct_Header);
      instance.SetStreamerFunc(&streamer_Header);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Header*)
   {
      return GenerateInitInstanceLocal((::Header*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Header*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Header::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Header::Class_Name()
{
   return "Header";
}

//______________________________________________________________________________
const char *Header::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Header*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Header::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Header*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Header::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Header*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Header::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Header*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Header::Streamer(TBuffer &R__b)
{
   // Stream an object of class Header.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> _POT_CountedPerFile;
      R__b >> _POT_NoCut;
      R__b >> _POT_BadBeam;
      R__b >> _POT_BadND280;
      R__b >> _POT_GoodBeamGoodND280;
      R__b >> _POT_0KA;
      R__b >> _POT_200KA;
      R__b >> _POT_250KA;
      R__b >> _POT_m250KA;
      R__b >> _POT_OtherKA;
      R__b >> _Spill_NoCut;
      R__b >> _Spill_BadBeam;
      R__b >> _Spill_BadND280;
      R__b >> _Spill_GoodBeamGoodND280;
      R__b >> _IsMC;
      { TString R__str; R__str.Streamer(R__b); _SoftwareVersion = R__str.Data(); }
      R__b.CheckByteCount(R__s, R__c, Header::IsA());
   } else {
      R__c = R__b.WriteVersion(Header::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << _POT_CountedPerFile;
      R__b << _POT_NoCut;
      R__b << _POT_BadBeam;
      R__b << _POT_BadND280;
      R__b << _POT_GoodBeamGoodND280;
      R__b << _POT_0KA;
      R__b << _POT_200KA;
      R__b << _POT_250KA;
      R__b << _POT_m250KA;
      R__b << _POT_OtherKA;
      R__b << _Spill_NoCut;
      R__b << _Spill_BadBeam;
      R__b << _Spill_BadND280;
      R__b << _Spill_GoodBeamGoodND280;
      R__b << _IsMC;
      { TString R__str = _SoftwareVersion.c_str(); R__str.Streamer(R__b);}
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void Header::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Header.
      TClass *R__cl = ::Header::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_CountedPerFile", &_POT_CountedPerFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_NoCut", &_POT_NoCut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_BadBeam", &_POT_BadBeam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_BadND280", &_POT_BadND280);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_GoodBeamGoodND280", &_POT_GoodBeamGoodND280);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_0KA", &_POT_0KA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_200KA", &_POT_200KA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_250KA", &_POT_250KA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_m250KA", &_POT_m250KA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_POT_OtherKA", &_POT_OtherKA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_Spill_NoCut", &_Spill_NoCut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_Spill_BadBeam", &_Spill_BadBeam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_Spill_BadND280", &_Spill_BadND280);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_Spill_GoodBeamGoodND280", &_Spill_GoodBeamGoodND280);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_IsMC", &_IsMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_SoftwareVersion", (void*)&_SoftwareVersion);
      R__insp.InspectMember("string", (void*)&_SoftwareVersion, "_SoftwareVersion.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_isFirstFile", &_isFirstFile);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Header(void *p) {
      return  p ? new(p) ::Header : new ::Header;
   }
   static void *newArray_Header(Long_t nElements, void *p) {
      return p ? new(p) ::Header[nElements] : new ::Header[nElements];
   }
   // Wrapper around operator delete
   static void delete_Header(void *p) {
      delete ((::Header*)p);
   }
   static void deleteArray_Header(void *p) {
      delete [] ((::Header*)p);
   }
   static void destruct_Header(void *p) {
      typedef ::Header current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Header(TBuffer &buf, void *obj) {
      ((::Header*)obj)->::Header::Streamer(buf);
   }
} // end of namespace ROOT for class ::Header

/********************************************************
* dict/Headerdict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableHeaderdict();

extern "C" void G__set_cpp_environmentHeaderdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/physics/home/mhogan/software/p0d-banff/p0d-banff/src/Header.hxx");
  G__cpp_reset_tagtableHeaderdict();
}
#include <new>
extern "C" int G__cpp_dllrevHeaderdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Header */
static int G__Headerdict_494_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Header* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Header[n];
     } else {
       p = new((void*) gvp) Header[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Header;
     } else {
       p = new((void*) gvp) Header;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HeaderdictLN_Header));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Header*) G__getstructoffset())->ReadHeader(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Header*) G__getstructoffset())->ReadHeader((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 103, (long) ((Header*) G__getstructoffset())->AddHeader(*(string*) libp->para[0].ref, (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((Header*) G__getstructoffset())->AddHeader(*(string*) libp->para[0].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 103, (long) ((Header*) G__getstructoffset())->AddHeader((TTree*) G__int(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((Header*) G__getstructoffset())->AddHeader((TTree*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOT());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Header*) G__getstructoffset())->GetNSpills());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTNoCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTCountedPerFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTBadBeam());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTBadND280());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTGoodBeamGoodND280());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOT0KA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOT200KA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOT250KA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTMinus250KA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Header*) G__getstructoffset())->GetPOTOtherKA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Header*) G__getstructoffset())->GetSpillNoCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Header*) G__getstructoffset())->GetSpillBadBeam());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Header*) G__getstructoffset())->GetSpillBadND280());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Header*) G__getstructoffset())->GetSpillGoodBeamGoodND280());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Header*) G__getstructoffset())->DumpPOT();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Header*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const Header*) G__getstructoffset())->GetIsMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((Header*) G__getstructoffset())->GetSoftwareVersion();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Header::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Header::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Header::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Header::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Header*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Header::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Header::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Header::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Headerdict_494_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Header::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Headerdict_494_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Header* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Header(*(Header*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HeaderdictLN_Header));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Header G__THeader;
static int G__Headerdict_494_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Header*) (soff+(sizeof(Header)*i)))->~G__THeader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Header*) (soff))->~G__THeader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Headerdict_494_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Header* dest = (Header*) G__getstructoffset();
   *dest = *(Header*) libp->para[0].ref;
   const Header& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Header */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncHeaderdict {
 public:
  G__Sizep2memfuncHeaderdict(): p(&G__Sizep2memfuncHeaderdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncHeaderdict::*p)();
};

size_t G__get_sizep2memfuncHeaderdict()
{
  G__Sizep2memfuncHeaderdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceHeaderdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__HeaderdictLN_Header))) {
     Header *G__Lderived;
     G__Lderived=(Header*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HeaderdictLN_Header),G__get_linked_tagnum(&G__HeaderdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableHeaderdict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Header */
static void G__setup_memvarHeader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__HeaderdictLN_Header));
   { Header *p; p=(Header*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->_POT_CountedPerFile)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_CountedPerFile=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_NoCut)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_NoCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_BadBeam)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_BadBeam=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_BadND280)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_BadND280=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_GoodBeamGoodND280)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_GoodBeamGoodND280=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_0KA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_0KA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_200KA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_200KA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_250KA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_250KA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_m250KA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_m250KA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_POT_OtherKA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"_POT_OtherKA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_Spill_NoCut)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"_Spill_NoCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_Spill_BadBeam)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"_Spill_BadBeam=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_Spill_BadND280)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"_Spill_BadND280=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_Spill_GoodBeamGoodND280)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"_Spill_GoodBeamGoodND280=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_IsMC)-(long)(p)),103,0,0,-1,-1,-1,1,"_IsMC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_SoftwareVersion)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__HeaderdictLN_string),-1,-1,1,"_SoftwareVersion=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_isFirstFile)-(long)(p)),103,0,0,-1,-1,-1,1,"_isFirstFile=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HeaderdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarHeaderdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncHeader(void) {
   /* Header */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__HeaderdictLN_Header));
   G__memfunc_setup("Header",585,G__Headerdict_494_0_1, 105, G__get_linked_tagnum(&G__HeaderdictLN_Header), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadHeader",965,G__Headerdict_494_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - file", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadHeader",965,G__Headerdict_494_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHeader",850,G__Headerdict_494_0_4, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - file g - - 0 'false' bySpillPOT", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHeader",850,G__Headerdict_494_0_5, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'TTree' - 0 - tree g - - 0 'false' bySpillPOT", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOT",531,G__Headerdict_494_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNSpills",997,G__Headerdict_494_0_7, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTNoCut",1020,G__Headerdict_494_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTCountedPerFile",1932,G__Headerdict_494_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTBadBeam",1167,G__Headerdict_494_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTBadND280",1094,G__Headerdict_494_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTGoodBeamGoodND280",1990,G__Headerdict_494_0_12, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOT0KA",719,G__Headerdict_494_0_13, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOT200KA",817,G__Headerdict_494_0_14, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOT250KA",822,G__Headerdict_494_0_15, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTMinus250KA",1346,G__Headerdict_494_0_16, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTOtherKA",1185,G__Headerdict_494_0_17, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSpillNoCut",1293,G__Headerdict_494_0_18, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSpillBadBeam",1440,G__Headerdict_494_0_19, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSpillBadND280",1367,G__Headerdict_494_0_20, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSpillGoodBeamGoodND280",2263,G__Headerdict_494_0_21, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DumpPOT",649,G__Headerdict_494_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__Headerdict_494_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIsMC",620,G__Headerdict_494_0_24, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSoftwareVersion",1873,G__Headerdict_494_0_25, 117, G__get_linked_tagnum(&G__HeaderdictLN_string), -1, 1, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Headerdict_494_0_26, 85, G__get_linked_tagnum(&G__HeaderdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Header::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Headerdict_494_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Header::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Headerdict_494_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Header::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Headerdict_494_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Header::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__HeaderdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Headerdict_494_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Headerdict_494_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Header::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Headerdict_494_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Header::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Headerdict_494_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Header::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Headerdict_494_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Header::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Header", 585, G__Headerdict_494_0_38, (int) ('i'), G__get_linked_tagnum(&G__HeaderdictLN_Header), -1, 0, 1, 1, 1, 0, "u 'Header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Header", 711, G__Headerdict_494_0_39, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Headerdict_494_0_40, (int) ('u'), G__get_linked_tagnum(&G__HeaderdictLN_Header), -1, 1, 1, 1, 1, 0, "u 'Header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncHeaderdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalHeaderdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcHeaderdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__HeaderdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__HeaderdictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__HeaderdictLN_Header = { "Header" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableHeaderdict() {
  G__HeaderdictLN_TClass.tagnum = -1 ;
  G__HeaderdictLN_TBuffer.tagnum = -1 ;
  G__HeaderdictLN_TMemberInspector.tagnum = -1 ;
  G__HeaderdictLN_TObject.tagnum = -1 ;
  G__HeaderdictLN_string.tagnum = -1 ;
  G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__HeaderdictLN_TTree.tagnum = -1 ;
  G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__HeaderdictLN_Header.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableHeaderdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_string);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_TTree);
   G__get_linked_tagnum_fwd(&G__HeaderdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__HeaderdictLN_Header),sizeof(Header),-1,29952,(char*)NULL,G__setup_memvarHeader,G__setup_memfuncHeader);
}
extern "C" void G__cpp_setupHeaderdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupHeaderdict()");
  G__set_cpp_environmentHeaderdict();
  G__cpp_setup_tagtableHeaderdict();

  G__cpp_setup_inheritanceHeaderdict();

  G__cpp_setup_typetableHeaderdict();

  G__cpp_setup_memvarHeaderdict();

  G__cpp_setup_memfuncHeaderdict();
  G__cpp_setup_globalHeaderdict();
  G__cpp_setup_funcHeaderdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncHeaderdict();
  return;
}
class G__cpp_setup_initHeaderdict {
  public:
    G__cpp_setup_initHeaderdict() { G__add_setup_func("Headerdict",(G__incsetup)(&G__cpp_setupHeaderdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initHeaderdict() { G__remove_setup_func("Headerdict"); }
};
G__cpp_setup_initHeaderdict G__cpp_setup_initializerHeaderdict;

