//
// File generated by /physics/software/t2k/ND280/v11r31/ROOT/v5r34p09n04/Linux-x86_64/bin/rootcint at Mon Dec 18 14:31:20 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictdIMakeClSampleSummarydict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "MakeClSampleSummarydict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MakeClSampleSummary_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_MakeClSampleSummary(void *p = 0);
   static void *newArray_MakeClSampleSummary(Long_t size, void *p);
   static void delete_MakeClSampleSummary(void *p);
   static void deleteArray_MakeClSampleSummary(void *p);
   static void destruct_MakeClSampleSummary(void *p);
   static void streamer_MakeClSampleSummary(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MakeClSampleSummary*)
   {
      ::MakeClSampleSummary *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MakeClSampleSummary >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MakeClSampleSummary", ::MakeClSampleSummary::Class_Version(), "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/MakeClSampleSummary.hxx", 20,
                  typeid(::MakeClSampleSummary), DefineBehavior(ptr, ptr),
                  &::MakeClSampleSummary::Dictionary, isa_proxy, 0,
                  sizeof(::MakeClSampleSummary) );
      instance.SetNew(&new_MakeClSampleSummary);
      instance.SetNewArray(&newArray_MakeClSampleSummary);
      instance.SetDelete(&delete_MakeClSampleSummary);
      instance.SetDeleteArray(&deleteArray_MakeClSampleSummary);
      instance.SetDestructor(&destruct_MakeClSampleSummary);
      instance.SetStreamerFunc(&streamer_MakeClSampleSummary);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MakeClSampleSummary*)
   {
      return GenerateInitInstanceLocal((::MakeClSampleSummary*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MakeClSampleSummary*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *MakeClSampleSummary::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *MakeClSampleSummary::Class_Name()
{
   return "MakeClSampleSummary";
}

//______________________________________________________________________________
const char *MakeClSampleSummary::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MakeClSampleSummary*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MakeClSampleSummary::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MakeClSampleSummary*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MakeClSampleSummary::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MakeClSampleSummary*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MakeClSampleSummary::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MakeClSampleSummary*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void MakeClSampleSummary::Streamer(TBuffer &R__b)
{
   // Stream an object of class MakeClSampleSummary.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> NSamples;
      R__b >> SelectedSample;
      R__b.ReadStaticArray((double*)Enu);
      R__b.ReadStaticArray((double*)Pmu);
      R__b.ReadStaticArray((double*)CosThetamu);
      R__b.ReadStaticArray((int*)ReactionCode);
      R__b.ReadStaticArray((int*)NeutrinoCode);
      R__b.ReadStaticArray((double*)FluxWeight);
      R__b.ReadStaticArray((double*)TruePmu);
      R__b.ReadStaticArray((double*)TrueCosThetamu);
      R__b.ReadStaticArray((double*)Q2);
      R__b.ReadStaticArray((double*)Q2QE);
      R__b.ReadStaticArray((char*)HaveTruth);
      R__b.ReadStaticArray((int*)TgtMat);
      R__b.ReadStaticArray((int*)NuParent);
      R__b >> Run;
      R__b.ReadStaticArray((int*)TruthVtx);
      R__b.ReadStaticArray((double*)CCQETuningWeight);
      R__b.ReadStaticArray((double*)CohTuningWeight);
      R__b.ReadStaticArray((double*)RFGTuningWeight);
      R__b.ReadStaticArray((double*)RelRPATuningWeight);
      R__b.ReadStaticArray((double*)NonRelRPATuningWeight);
      MAQEGraph->Streamer(R__b);
      Q3CUTGraph->Streamer(R__b);
      MEC_CGraph->Streamer(R__b);
      PF_CGraph->Streamer(R__b);
      MEC_OGraph->Streamer(R__b);
      PF_OGraph->Streamer(R__b);
      CA5Graph->Streamer(R__b);
      MARESGraph->Streamer(R__b);
      BgSclResGraph->Streamer(R__b);
      CCNuEGraph->Streamer(R__b);
      DISMPiShpGraph->Streamer(R__b);
      FSI_PI_ABSGraph->Streamer(R__b);
      FSI_CEX_LOGraph->Streamer(R__b);
      FSI_INEL_LOGraph->Streamer(R__b);
      FSI_PI_PRODGraph->Streamer(R__b);
      FSI_CEX_HIGraph->Streamer(R__b);
      FSI_INEL_HIGraph->Streamer(R__b);
      PDD_CGraph->Streamer(R__b);
      PDD_OGraph->Streamer(R__b);
      SF_RFGGraph->Streamer(R__b);
      RPAGraph->Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, MakeClSampleSummary::IsA());
   } else {
      R__c = R__b.WriteVersion(MakeClSampleSummary::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << NSamples;
      R__b << SelectedSample;
      R__b.WriteArray(Enu, 89);
      R__b.WriteArray(Pmu, 89);
      R__b.WriteArray(CosThetamu, 89);
      R__b.WriteArray(ReactionCode, 89);
      R__b.WriteArray(NeutrinoCode, 89);
      R__b.WriteArray(FluxWeight, 89);
      R__b.WriteArray(TruePmu, 89);
      R__b.WriteArray(TrueCosThetamu, 89);
      R__b.WriteArray(Q2, 89);
      R__b.WriteArray(Q2QE, 89);
      R__b.WriteArray(HaveTruth, 89);
      R__b.WriteArray(TgtMat, 89);
      R__b.WriteArray(NuParent, 89);
      R__b << Run;
      R__b.WriteArray(TruthVtx, 89);
      R__b.WriteArray(CCQETuningWeight, 89);
      R__b.WriteArray(CohTuningWeight, 89);
      R__b.WriteArray(RFGTuningWeight, 89);
      R__b.WriteArray(RelRPATuningWeight, 89);
      R__b.WriteArray(NonRelRPATuningWeight, 89);
      MAQEGraph->Streamer(R__b);
      Q3CUTGraph->Streamer(R__b);
      MEC_CGraph->Streamer(R__b);
      PF_CGraph->Streamer(R__b);
      MEC_OGraph->Streamer(R__b);
      PF_OGraph->Streamer(R__b);
      CA5Graph->Streamer(R__b);
      MARESGraph->Streamer(R__b);
      BgSclResGraph->Streamer(R__b);
      CCNuEGraph->Streamer(R__b);
      DISMPiShpGraph->Streamer(R__b);
      FSI_PI_ABSGraph->Streamer(R__b);
      FSI_CEX_LOGraph->Streamer(R__b);
      FSI_INEL_LOGraph->Streamer(R__b);
      FSI_PI_PRODGraph->Streamer(R__b);
      FSI_CEX_HIGraph->Streamer(R__b);
      FSI_INEL_HIGraph->Streamer(R__b);
      PDD_CGraph->Streamer(R__b);
      PDD_OGraph->Streamer(R__b);
      SF_RFGGraph->Streamer(R__b);
      RPAGraph->Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void MakeClSampleSummary::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MakeClSampleSummary.
      TClass *R__cl = ::MakeClSampleSummary::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCurrent", &fCurrent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NSamples", &NSamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SelectedSample", &SelectedSample);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Enu[89]", Enu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Pmu[89]", Pmu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "CosThetamu[89]", CosThetamu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ReactionCode[89]", ReactionCode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NeutrinoCode[89]", NeutrinoCode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FluxWeight[89]", FluxWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TruePmu[89]", TruePmu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrueCosThetamu[89]", TrueCosThetamu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Q2[89]", Q2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Q2QE[89]", Q2QE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "HaveTruth[89]", HaveTruth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TgtMat[89]", TgtMat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NuParent[89]", NuParent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Run", &Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TruthVtx[89]", TruthVtx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "CCQETuningWeight[89]", CCQETuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "CohTuningWeight[89]", CohTuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RFGTuningWeight[89]", RFGTuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RelRPATuningWeight[89]", RelRPATuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NonRelRPATuningWeight[89]", NonRelRPATuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*MAQEGraph", &MAQEGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Q3CUTGraph", &Q3CUTGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*MEC_CGraph", &MEC_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PF_CGraph", &PF_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*MEC_OGraph", &MEC_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PF_OGraph", &PF_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*CA5Graph", &CA5Graph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*MARESGraph", &MARESGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*BgSclResGraph", &BgSclResGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*CCNuEGraph", &CCNuEGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*DISMPiShpGraph", &DISMPiShpGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_PI_ABSGraph", &FSI_PI_ABSGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_CEX_LOGraph", &FSI_CEX_LOGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_INEL_LOGraph", &FSI_INEL_LOGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_PI_PRODGraph", &FSI_PI_PRODGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_CEX_HIGraph", &FSI_CEX_HIGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*FSI_INEL_HIGraph", &FSI_INEL_HIGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PDD_CGraph", &PDD_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PDD_OGraph", &PDD_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*SF_RFGGraph", &SF_RFGGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*RPAGraph", &RPAGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NSamples", &b_NSamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_SelectedSample", &b_SelectedSample);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Enu", &b_Enu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Pmu", &b_Pmu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CosThetamu", &b_CosThetamu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ReactionCode", &b_ReactionCode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NeutrinoCode", &b_NeutrinoCode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FluxWeight", &b_FluxWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TruePmu", &b_TruePmu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrueCosThetamu", &b_TrueCosThetamu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q2", &b_Q2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q2QE", &b_Q2QE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_HaveTruth", &b_HaveTruth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TgtMat", &b_TgtMat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NuParent", &b_NuParent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Run", &b_Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TruthVtx", &b_TruthVtx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CCQETuningWeight", &b_CCQETuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CohTuningWeight", &b_CohTuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RFGTuningWeight", &b_RFGTuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RelRPATuningWeight", &b_RelRPATuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NonRelRPATuningWeight", &b_NonRelRPATuningWeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MAQEGraph", &b_MAQEGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q3CUTGraph", &b_Q3CUTGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MEC_CGraph", &b_MEC_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PF_CGraph", &b_PF_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MEC_OGraph", &b_MEC_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PF_OGraph", &b_PF_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CA5Graph", &b_CA5Graph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MARESGraph", &b_MARESGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_BgSclResGraph", &b_BgSclResGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CCNuEGraph", &b_CCNuEGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_DISMPiShpGraph", &b_DISMPiShpGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_PI_ABSGraph", &b_FSI_PI_ABSGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_CEX_LOGraph", &b_FSI_CEX_LOGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_INEL_LOGraph", &b_FSI_INEL_LOGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_PI_PRODGraph", &b_FSI_PI_PRODGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_CEX_HIGraph", &b_FSI_CEX_HIGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_FSI_INEL_HIGraph", &b_FSI_INEL_HIGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PDD_CGraph", &b_PDD_CGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PDD_OGraph", &b_PDD_OGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_SF_RFGGraph", &b_SF_RFGGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RPAGraph", &b_RPAGraph);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_MakeClSampleSummary(void *p) {
      return  p ? new(p) ::MakeClSampleSummary : new ::MakeClSampleSummary;
   }
   static void *newArray_MakeClSampleSummary(Long_t nElements, void *p) {
      return p ? new(p) ::MakeClSampleSummary[nElements] : new ::MakeClSampleSummary[nElements];
   }
   // Wrapper around operator delete
   static void delete_MakeClSampleSummary(void *p) {
      delete ((::MakeClSampleSummary*)p);
   }
   static void deleteArray_MakeClSampleSummary(void *p) {
      delete [] ((::MakeClSampleSummary*)p);
   }
   static void destruct_MakeClSampleSummary(void *p) {
      typedef ::MakeClSampleSummary current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_MakeClSampleSummary(TBuffer &buf, void *obj) {
      ((::MakeClSampleSummary*)obj)->::MakeClSampleSummary::Streamer(buf);
   }
} // end of namespace ROOT for class ::MakeClSampleSummary

/********************************************************
* dict/MakeClSampleSummarydict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableMakeClSampleSummarydict();

extern "C" void G__set_cpp_environmentMakeClSampleSummarydict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/physics/home/mhogan/software/p0d-banff/p0d-banff/src/MakeClSampleSummary.hxx");
  G__cpp_reset_tagtableMakeClSampleSummarydict();
}
#include <new>
extern "C" int G__cpp_dllrevMakeClSampleSummarydict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MakeClSampleSummary */
static int G__MakeClSampleSummarydict_543_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MakeClSampleSummary* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MakeClSampleSummary((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) MakeClSampleSummary((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new MakeClSampleSummary[n];
       } else {
         p = new((void*) gvp) MakeClSampleSummary[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new MakeClSampleSummary;
       } else {
         p = new((void*) gvp) MakeClSampleSummary;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MakeClSampleSummary*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MakeClSampleSummary*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((MakeClSampleSummary*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MakeClSampleSummary*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MakeClSampleSummary*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((MakeClSampleSummary*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((MakeClSampleSummary*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MakeClSampleSummary::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MakeClSampleSummary::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MakeClSampleSummary::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MakeClSampleSummary::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MakeClSampleSummary*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MakeClSampleSummary::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MakeClSampleSummary::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MakeClSampleSummary::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MakeClSampleSummarydict_543_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MakeClSampleSummary::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MakeClSampleSummarydict_543_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MakeClSampleSummary* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MakeClSampleSummary(*(MakeClSampleSummary*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MakeClSampleSummary G__TMakeClSampleSummary;
static int G__MakeClSampleSummarydict_543_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MakeClSampleSummary*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MakeClSampleSummary*) (soff+(sizeof(MakeClSampleSummary)*i)))->~G__TMakeClSampleSummary();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MakeClSampleSummary*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MakeClSampleSummary*) (soff))->~G__TMakeClSampleSummary();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__MakeClSampleSummarydict_543_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MakeClSampleSummary* dest = (MakeClSampleSummary*) G__getstructoffset();
   *dest = *(MakeClSampleSummary*) libp->para[0].ref;
   const MakeClSampleSummary& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MakeClSampleSummary */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMakeClSampleSummarydict {
 public:
  G__Sizep2memfuncMakeClSampleSummarydict(): p(&G__Sizep2memfuncMakeClSampleSummarydict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMakeClSampleSummarydict::*p)();
};

size_t G__get_sizep2memfuncMakeClSampleSummarydict()
{
  G__Sizep2memfuncMakeClSampleSummarydict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMakeClSampleSummarydict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary))) {
     MakeClSampleSummary *G__Lderived;
     G__Lderived=(MakeClSampleSummary*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary),G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMakeClSampleSummarydict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MakeClSampleSummary */
static void G__setup_memvarMakeClSampleSummary(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary));
   { MakeClSampleSummary *p; p=(MakeClSampleSummary*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->NSamples)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"NSamples=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SelectedSample)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"SelectedSample=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Enu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Enu[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->Pmu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Pmu[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->CosThetamu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"CosThetamu[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->ReactionCode)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ReactionCode[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->NeutrinoCode)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"NeutrinoCode[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->FluxWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"FluxWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->TruePmu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TruePmu[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->TrueCosThetamu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TrueCosThetamu[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->Q2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Q2[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->Q2QE)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Q2QE[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->HaveTruth)-(long)(p)),99,0,0,-1,G__defined_typename("Char_t"),-1,1,"HaveTruth[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->TgtMat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TgtMat[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->NuParent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"NuParent[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->Run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TruthVtx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TruthVtx[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->CCQETuningWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"CCQETuningWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->CohTuningWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"CohTuningWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->RFGTuningWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"RFGTuningWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->RelRPATuningWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"RelRPATuningWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->NonRelRPATuningWeight)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"NonRelRPATuningWeight[89]=",0,"[NSamples]");
   G__memvar_setup((void*)((long)(&p->MAQEGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"MAQEGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Q3CUTGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"Q3CUTGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MEC_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"MEC_CGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PF_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"PF_CGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MEC_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"MEC_OGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PF_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"PF_OGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->CA5Graph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"CA5Graph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MARESGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"MARESGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->BgSclResGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"BgSclResGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->CCNuEGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"CCNuEGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->DISMPiShpGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"DISMPiShpGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_PI_ABSGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_PI_ABSGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_CEX_LOGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_CEX_LOGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_INEL_LOGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_INEL_LOGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_PI_PRODGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_PI_PRODGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_CEX_HIGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_CEX_HIGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FSI_INEL_HIGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"FSI_INEL_HIGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PDD_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"PDD_CGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PDD_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"PDD_OGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SF_RFGGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"SF_RFGGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->RPAGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClonesArray),-1,-1,1,"RPAGraph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_NSamples)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_NSamples=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_SelectedSample)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_SelectedSample=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Enu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Enu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Pmu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Pmu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CosThetamu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_CosThetamu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ReactionCode)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_ReactionCode=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NeutrinoCode)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_NeutrinoCode=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FluxWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FluxWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TruePmu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_TruePmu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrueCosThetamu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_TrueCosThetamu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Q2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q2QE)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Q2QE=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_HaveTruth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_HaveTruth=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TgtMat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_TgtMat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NuParent)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_NuParent=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Run)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Run=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TruthVtx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_TruthVtx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CCQETuningWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_CCQETuningWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CohTuningWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_CohTuningWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RFGTuningWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_RFGTuningWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RelRPATuningWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_RelRPATuningWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NonRelRPATuningWeight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_NonRelRPATuningWeight=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MAQEGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_MAQEGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q3CUTGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_Q3CUTGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MEC_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_MEC_CGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PF_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_PF_CGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MEC_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_MEC_OGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PF_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_PF_OGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CA5Graph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_CA5Graph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MARESGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_MARESGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_BgSclResGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_BgSclResGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CCNuEGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_CCNuEGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DISMPiShpGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_DISMPiShpGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_PI_ABSGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_PI_ABSGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_CEX_LOGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_CEX_LOGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_INEL_LOGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_INEL_LOGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_PI_PRODGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_PI_PRODGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_CEX_HIGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_CEX_HIGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_FSI_INEL_HIGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_FSI_INEL_HIGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PDD_CGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_PDD_CGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PDD_OGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_PDD_OGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_SF_RFGGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_SF_RFGGraph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RPAGraph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TBranch),-1,-1,1,"b_RPAGraph=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMakeClSampleSummarydict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMakeClSampleSummary(void) {
   /* MakeClSampleSummary */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary));
   G__memfunc_setup("MakeClSampleSummary",1917,G__MakeClSampleSummarydict_543_0_1, 105, G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__MakeClSampleSummarydict_543_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__MakeClSampleSummarydict_543_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__MakeClSampleSummarydict_543_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__MakeClSampleSummarydict_543_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__MakeClSampleSummarydict_543_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__MakeClSampleSummarydict_543_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__MakeClSampleSummarydict_543_0_9, 85, G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MakeClSampleSummary::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__MakeClSampleSummarydict_543_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MakeClSampleSummary::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__MakeClSampleSummarydict_543_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MakeClSampleSummary::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__MakeClSampleSummarydict_543_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MakeClSampleSummary::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MakeClSampleSummarydict_543_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__MakeClSampleSummarydict_543_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MakeClSampleSummary::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__MakeClSampleSummarydict_543_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MakeClSampleSummary::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__MakeClSampleSummarydict_543_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MakeClSampleSummary::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__MakeClSampleSummarydict_543_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MakeClSampleSummary::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("MakeClSampleSummary", 1917, G__MakeClSampleSummarydict_543_0_21, (int) ('i'), G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary), -1, 0, 1, 1, 1, 0, "u 'MakeClSampleSummary' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MakeClSampleSummary", 2043, G__MakeClSampleSummarydict_543_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__MakeClSampleSummarydict_543_0_23, (int) ('u'), G__get_linked_tagnum(&G__MakeClSampleSummarydictLN_MakeClSampleSummary), -1, 1, 1, 1, 1, 0, "u 'MakeClSampleSummary' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMakeClSampleSummarydict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMakeClSampleSummarydict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMakeClSampleSummarydict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MakeClSampleSummarydictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__MakeClSampleSummarydictLN_MakeClSampleSummary = { "MakeClSampleSummary" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMakeClSampleSummarydict() {
  G__MakeClSampleSummarydictLN_TClass.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TBuffer.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TMemberInspector.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TObject.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TClonesArray.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TTree.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_TBranch.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__MakeClSampleSummarydictLN_MakeClSampleSummary.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMakeClSampleSummarydict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TClass);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TObject);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TTree);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__MakeClSampleSummarydictLN_MakeClSampleSummary),sizeof(MakeClSampleSummary),-1,29952,(char*)NULL,G__setup_memvarMakeClSampleSummary,G__setup_memfuncMakeClSampleSummary);
}
extern "C" void G__cpp_setupMakeClSampleSummarydict(void) {
  G__check_setup_version(30051515,"G__cpp_setupMakeClSampleSummarydict()");
  G__set_cpp_environmentMakeClSampleSummarydict();
  G__cpp_setup_tagtableMakeClSampleSummarydict();

  G__cpp_setup_inheritanceMakeClSampleSummarydict();

  G__cpp_setup_typetableMakeClSampleSummarydict();

  G__cpp_setup_memvarMakeClSampleSummarydict();

  G__cpp_setup_memfuncMakeClSampleSummarydict();
  G__cpp_setup_globalMakeClSampleSummarydict();
  G__cpp_setup_funcMakeClSampleSummarydict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMakeClSampleSummarydict();
  return;
}
class G__cpp_setup_initMakeClSampleSummarydict {
  public:
    G__cpp_setup_initMakeClSampleSummarydict() { G__add_setup_func("MakeClSampleSummarydict",(G__incsetup)(&G__cpp_setupMakeClSampleSummarydict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMakeClSampleSummarydict() { G__remove_setup_func("MakeClSampleSummarydict"); }
};
G__cpp_setup_initMakeClSampleSummarydict G__cpp_setup_initializerMakeClSampleSummarydict;

