/********************************************************************
* dict/MakeClSampleSummarydict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/MakeClSampleSummarydict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMakeClSampleSummarydict();
extern void G__cpp_setup_inheritanceMakeClSampleSummarydict();
extern void G__cpp_setup_typetableMakeClSampleSummarydict();
extern void G__cpp_setup_memvarMakeClSampleSummarydict();
extern void G__cpp_setup_globalMakeClSampleSummarydict();
extern void G__cpp_setup_memfuncMakeClSampleSummarydict();
extern void G__cpp_setup_funcMakeClSampleSummarydict();
extern void G__set_cpp_environmentMakeClSampleSummarydict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/MakeClSampleSummary.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MakeClSampleSummarydictLN_TClass;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TBuffer;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TMemberInspector;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TObject;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TClonesArray;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TTree;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_TBranch;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MakeClSampleSummarydictLN_MakeClSampleSummary;

/* STUB derived class for protected member access */
