/********************************************************************
* dict/MakeClFlatTreedict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/MakeClFlatTreedict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMakeClFlatTreedict();
extern void G__cpp_setup_inheritanceMakeClFlatTreedict();
extern void G__cpp_setup_typetableMakeClFlatTreedict();
extern void G__cpp_setup_memvarMakeClFlatTreedict();
extern void G__cpp_setup_globalMakeClFlatTreedict();
extern void G__cpp_setup_memfuncMakeClFlatTreedict();
extern void G__cpp_setup_funcMakeClFlatTreedict();
extern void G__set_cpp_environmentMakeClFlatTreedict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/MakeClFlatTree.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MakeClFlatTreedictLN_TClass;
extern G__linked_taginfo G__MakeClFlatTreedictLN_TBuffer;
extern G__linked_taginfo G__MakeClFlatTreedictLN_TMemberInspector;
extern G__linked_taginfo G__MakeClFlatTreedictLN_TObject;
extern G__linked_taginfo G__MakeClFlatTreedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_TTree;
extern G__linked_taginfo G__MakeClFlatTreedictLN_TBranch;
extern G__linked_taginfo G__MakeClFlatTreedictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MakeClFlatTreedictLN_MakeClFlatTree;

/* STUB derived class for protected member access */
