/********************************************************************
* dict/P0DBANFFInterfacedict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/P0DBANFFInterfacedict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableP0DBANFFInterfacedict();
extern void G__cpp_setup_inheritanceP0DBANFFInterfacedict();
extern void G__cpp_setup_typetableP0DBANFFInterfacedict();
extern void G__cpp_setup_memvarP0DBANFFInterfacedict();
extern void G__cpp_setup_globalP0DBANFFInterfacedict();
extern void G__cpp_setup_memfuncP0DBANFFInterfacedict();
extern void G__cpp_setup_funcP0DBANFFInterfacedict();
extern void G__set_cpp_environmentP0DBANFFInterfacedict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/P0DBANFFInterface.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TClass;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TBuffer;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TMemberInspector;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TObject;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TString;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_TColor;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_P0DBANFFInterface;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
