//
// File generated by /physics/software/t2k/ND280/v11r31/ROOT/v5r34p09n04/Linux-x86_64/bin/rootcint at Mon Dec 18 14:31:25 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictdIP0DBANFFInterfacedict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "P0DBANFFInterfacedict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void P0DBANFFInterface_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_P0DBANFFInterface(void *p = 0);
   static void *newArray_P0DBANFFInterface(Long_t size, void *p);
   static void delete_P0DBANFFInterface(void *p);
   static void deleteArray_P0DBANFFInterface(void *p);
   static void destruct_P0DBANFFInterface(void *p);
   static void streamer_P0DBANFFInterface(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::P0DBANFFInterface*)
   {
      ::P0DBANFFInterface *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::P0DBANFFInterface >(0);
      static ::ROOT::TGenericClassInfo 
         instance("P0DBANFFInterface", ::P0DBANFFInterface::Class_Version(), "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/P0DBANFFInterface.hxx", 6,
                  typeid(::P0DBANFFInterface), DefineBehavior(ptr, ptr),
                  &::P0DBANFFInterface::Dictionary, isa_proxy, 0,
                  sizeof(::P0DBANFFInterface) );
      instance.SetNew(&new_P0DBANFFInterface);
      instance.SetNewArray(&newArray_P0DBANFFInterface);
      instance.SetDelete(&delete_P0DBANFFInterface);
      instance.SetDeleteArray(&deleteArray_P0DBANFFInterface);
      instance.SetDestructor(&destruct_P0DBANFFInterface);
      instance.SetStreamerFunc(&streamer_P0DBANFFInterface);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::P0DBANFFInterface*)
   {
      return GenerateInitInstanceLocal((::P0DBANFFInterface*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::P0DBANFFInterface*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *P0DBANFFInterface::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *P0DBANFFInterface::Class_Name()
{
   return "P0DBANFFInterface";
}

//______________________________________________________________________________
const char *P0DBANFFInterface::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::P0DBANFFInterface*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int P0DBANFFInterface::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::P0DBANFFInterface*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void P0DBANFFInterface::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::P0DBANFFInterface*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *P0DBANFFInterface::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::P0DBANFFInterface*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void P0DBANFFInterface::Streamer(TBuffer &R__b)
{
   // Stream an object of class P0DBANFFInterface.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> cbBlack;
      R__b >> cbOrange;
      R__b >> cbSky;
      R__b >> cbGreen;
      R__b >> cbBlue;
      R__b >> cbRed;
      R__b >> cbPurple;
      R__b >> cbYellow;
      R__b.CheckByteCount(R__s, R__c, P0DBANFFInterface::IsA());
   } else {
      R__c = R__b.WriteVersion(P0DBANFFInterface::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << cbBlack;
      R__b << cbOrange;
      R__b << cbSky;
      R__b << cbGreen;
      R__b << cbBlue;
      R__b << cbRed;
      R__b << cbPurple;
      R__b << cbYellow;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void P0DBANFFInterface::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class P0DBANFFInterface.
      TClass *R__cl = ::P0DBANFFInterface::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbBlack", &cbBlack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbOrange", &cbOrange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbSky", &cbSky);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbGreen", &cbGreen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbBlue", &cbBlue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbRed", &cbRed);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbPurple", &cbPurple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cbYellow", &cbYellow);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_P0DBANFFInterface(void *p) {
      return  p ? new(p) ::P0DBANFFInterface : new ::P0DBANFFInterface;
   }
   static void *newArray_P0DBANFFInterface(Long_t nElements, void *p) {
      return p ? new(p) ::P0DBANFFInterface[nElements] : new ::P0DBANFFInterface[nElements];
   }
   // Wrapper around operator delete
   static void delete_P0DBANFFInterface(void *p) {
      delete ((::P0DBANFFInterface*)p);
   }
   static void deleteArray_P0DBANFFInterface(void *p) {
      delete [] ((::P0DBANFFInterface*)p);
   }
   static void destruct_P0DBANFFInterface(void *p) {
      typedef ::P0DBANFFInterface current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_P0DBANFFInterface(TBuffer &buf, void *obj) {
      ((::P0DBANFFInterface*)obj)->::P0DBANFFInterface::Streamer(buf);
   }
} // end of namespace ROOT for class ::P0DBANFFInterface

/********************************************************
* dict/P0DBANFFInterfacedict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableP0DBANFFInterfacedict();

extern "C" void G__set_cpp_environmentP0DBANFFInterfacedict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/physics/home/mhogan/software/p0d-banff/p0d-banff/src/P0DBANFFInterface.hxx");
  G__cpp_reset_tagtableP0DBANFFInterfacedict();
}
#include <new>
extern "C" int G__cpp_dllrevP0DBANFFInterfacedict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* P0DBANFFInterface */
static int G__P0DBANFFInterfacedict_186_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P0DBANFFInterface* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new P0DBANFFInterface[n];
     } else {
       p = new((void*) gvp) P0DBANFFInterface[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new P0DBANFFInterface;
     } else {
       p = new((void*) gvp) P0DBANFFInterface;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((const P0DBANFFInterface*) G__getstructoffset())->LoadColorBlindPalette((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((const P0DBANFFInterface*) G__getstructoffset())->LoadColorBlindPalette();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const P0DBANFFInterface*) G__getstructoffset())->CheckFile(*(TString*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((const P0DBANFFInterface*) G__getstructoffset())->RandomSleep(*(Int_t*) G__Intref(&libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((const P0DBANFFInterface*) G__getstructoffset())->RandomSleep(*(Int_t*) G__Intref(&libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TString>* pobj;
         vector<TString> xobj = ((P0DBANFFInterface*) G__getstructoffset())->SplitString(*(TString*) libp->para[0].ref, (const Char_t) G__int(libp->para[1]));
         pobj = new vector<TString>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ((P0DBANFFInterface*) G__getstructoffset())->SaveCanvasAs(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref
, *(TString*) libp->para[2].ref, *(TString*) libp->para[3].ref
, (const Char_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((P0DBANFFInterface*) G__getstructoffset())->SaveCanvasAs(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref
, *(TString*) libp->para[2].ref, *(TString*) libp->para[3].ref);
      G__setnull(result7);
      break;
   case 3:
      ((P0DBANFFInterface*) G__getstructoffset())->SaveCanvasAs(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref
, *(TString*) libp->para[2].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) P0DBANFFInterface::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P0DBANFFInterface::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) P0DBANFFInterface::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      P0DBANFFInterface::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P0DBANFFInterface*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P0DBANFFInterface::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) P0DBANFFInterface::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P0DBANFFInterface::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__P0DBANFFInterfacedict_186_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) P0DBANFFInterface::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__P0DBANFFInterfacedict_186_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   P0DBANFFInterface* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new P0DBANFFInterface(*(P0DBANFFInterface*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef P0DBANFFInterface G__TP0DBANFFInterface;
static int G__P0DBANFFInterfacedict_186_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (P0DBANFFInterface*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((P0DBANFFInterface*) (soff+(sizeof(P0DBANFFInterface)*i)))->~G__TP0DBANFFInterface();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (P0DBANFFInterface*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((P0DBANFFInterface*) (soff))->~G__TP0DBANFFInterface();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__P0DBANFFInterfacedict_186_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P0DBANFFInterface* dest = (P0DBANFFInterface*) G__getstructoffset();
   *dest = *(P0DBANFFInterface*) libp->para[0].ref;
   const P0DBANFFInterface& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* P0DBANFFInterface */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncP0DBANFFInterfacedict {
 public:
  G__Sizep2memfuncP0DBANFFInterfacedict(): p(&G__Sizep2memfuncP0DBANFFInterfacedict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncP0DBANFFInterfacedict::*p)();
};

size_t G__get_sizep2memfuncP0DBANFFInterfacedict()
{
  G__Sizep2memfuncP0DBANFFInterfacedict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceP0DBANFFInterfacedict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface))) {
     P0DBANFFInterface *G__Lderived;
     G__Lderived=(P0DBANFFInterface*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface),G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableP0DBANFFInterfacedict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* P0DBANFFInterface */
static void G__setup_memvarP0DBANFFInterface(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface));
   { P0DBANFFInterface *p; p=(P0DBANFFInterface*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,103,0,1,-1,G__defined_typename("Bool_t"),-2,1,G__FastAllocString(2048).Format("GoodFile=%lldLL",(long long)P0DBANFFInterface::GoodFile).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,103,0,1,-1,G__defined_typename("Bool_t"),-2,1,G__FastAllocString(2048).Format("BadFile=%lldLL",(long long)P0DBANFFInterface::BadFile).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,103,0,1,-1,G__defined_typename("Bool_t"),-2,1,G__FastAllocString(2048).Format("GoodStatus=%lldLL",(long long)P0DBANFFInterface::GoodStatus).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,103,0,1,-1,G__defined_typename("Bool_t"),-2,1,G__FastAllocString(2048).Format("BadStatus=%lldLL",(long long)P0DBANFFInterface::BadStatus).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbBlack=%lldLL",(long long)P0DBANFFInterface::kcbBlack).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbOrange=%lldLL",(long long)P0DBANFFInterface::kcbOrange).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbSky=%lldLL",(long long)P0DBANFFInterface::kcbSky).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbGreen=%lldLL",(long long)P0DBANFFInterface::kcbGreen).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbBlue=%lldLL",(long long)P0DBANFFInterface::kcbBlue).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbRed=%lldLL",(long long)P0DBANFFInterface::kcbRed).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbPurple=%lldLL",(long long)P0DBANFFInterface::kcbPurple).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("Int_t"),-2,1,G__FastAllocString(2048).Format("kcbYellow=%lldLL",(long long)P0DBANFFInterface::kcbYellow).data(),0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbBlack)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbBlack=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbOrange)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbOrange=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbSky)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbSky=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbGreen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbGreen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbBlue)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbBlue=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbRed)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbRed=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbPurple)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbPurple=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cbYellow)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TColor),-1,-1,1,"cbYellow=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarP0DBANFFInterfacedict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncP0DBANFFInterface(void) {
   /* P0DBANFFInterface */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface));
   G__memfunc_setup("P0DBANFFInterface",1458,G__P0DBANFFInterfacedict_186_0_1, 105, G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadColorBlindPalette",2103,G__P0DBANFFInterfacedict_186_0_2, 121, -1, -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 '5' nColors", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckFile",862,G__P0DBANFFInterfacedict_186_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 8, "u 'TString' - 1 - fileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RandomSleep",1114,G__P0DBANFFInterfacedict_186_0_4, 121, -1, -1, 0, 2, 1, 1, 8, 
"i - 'Int_t' 11 - nSeconds i - 'Int_t' 0 '0' seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SplitString",1155,G__P0DBANFFInterfacedict_186_0_5, 117, G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR), G__defined_typename("vector<TString>"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - theOpt c - 'Char_t' 10 - separator", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveCanvasAs",1183,G__P0DBANFFInterfacedict_186_0_6, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 1 - inputFileName u 'TString' - 11 - canvasName "
"u 'TString' - 11 - outputNamePrefix u 'TString' - 11 '\"eps,png,pdf\"' formats "
"c - 'Char_t' 10 '','' delimiter", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__P0DBANFFInterfacedict_186_0_7, 85, G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&P0DBANFFInterface::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__P0DBANFFInterfacedict_186_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P0DBANFFInterface::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__P0DBANFFInterfacedict_186_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&P0DBANFFInterface::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__P0DBANFFInterfacedict_186_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&P0DBANFFInterface::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__P0DBANFFInterfacedict_186_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__P0DBANFFInterfacedict_186_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P0DBANFFInterface::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__P0DBANFFInterfacedict_186_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&P0DBANFFInterface::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__P0DBANFFInterfacedict_186_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P0DBANFFInterface::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__P0DBANFFInterfacedict_186_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&P0DBANFFInterface::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("P0DBANFFInterface", 1458, G__P0DBANFFInterfacedict_186_0_19, (int) ('i'), G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface), -1, 0, 1, 1, 1, 0, "u 'P0DBANFFInterface' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~P0DBANFFInterface", 1584, G__P0DBANFFInterfacedict_186_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__P0DBANFFInterfacedict_186_0_21, (int) ('u'), G__get_linked_tagnum(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface), -1, 1, 1, 1, 1, 0, "u 'P0DBANFFInterface' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncP0DBANFFInterfacedict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalP0DBANFFInterfacedict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcP0DBANFFInterfacedict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__P0DBANFFInterfacedictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_TColor = { "TColor" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_P0DBANFFInterface = { "P0DBANFFInterface" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableP0DBANFFInterfacedict() {
  G__P0DBANFFInterfacedictLN_TClass.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_TBuffer.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_TMemberInspector.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_TObject.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_TString.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_TColor.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_P0DBANFFInterface.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableP0DBANFFInterfacedict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TClass);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TObject);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TString);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_TColor);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_P0DBANFFInterface),sizeof(P0DBANFFInterface),-1,29952,(char*)NULL,G__setup_memvarP0DBANFFInterface,G__setup_memfuncP0DBANFFInterface);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__P0DBANFFInterfacedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupP0DBANFFInterfacedict(void) {
  G__check_setup_version(30051515,"G__cpp_setupP0DBANFFInterfacedict()");
  G__set_cpp_environmentP0DBANFFInterfacedict();
  G__cpp_setup_tagtableP0DBANFFInterfacedict();

  G__cpp_setup_inheritanceP0DBANFFInterfacedict();

  G__cpp_setup_typetableP0DBANFFInterfacedict();

  G__cpp_setup_memvarP0DBANFFInterfacedict();

  G__cpp_setup_memfuncP0DBANFFInterfacedict();
  G__cpp_setup_globalP0DBANFFInterfacedict();
  G__cpp_setup_funcP0DBANFFInterfacedict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncP0DBANFFInterfacedict();
  return;
}
class G__cpp_setup_initP0DBANFFInterfacedict {
  public:
    G__cpp_setup_initP0DBANFFInterfacedict() { G__add_setup_func("P0DBANFFInterfacedict",(G__incsetup)(&G__cpp_setupP0DBANFFInterfacedict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initP0DBANFFInterfacedict() { G__remove_setup_func("P0DBANFFInterfacedict"); }
};
G__cpp_setup_initP0DBANFFInterfacedict G__cpp_setup_initializerP0DBANFFInterfacedict;

