//
// File generated by /physics/software/t2k/ND280/v11r31/ROOT/v5r34p09n04/Linux-x86_64/bin/rootcint at Mon Dec 18 14:31:28 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictdITotalPOTdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TotalPOTdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TotalPOT_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void TotalPOT_Dictionary();
   static void *new_TotalPOT(void *p = 0);
   static void *newArray_TotalPOT(Long_t size, void *p);
   static void delete_TotalPOT(void *p);
   static void deleteArray_TotalPOT(void *p);
   static void destruct_TotalPOT(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TotalPOT*)
   {
      ::TotalPOT *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TotalPOT),0);
      static ::ROOT::TGenericClassInfo 
         instance("TotalPOT", "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/TotalPOT.hxx", 14,
                  typeid(::TotalPOT), DefineBehavior(ptr, ptr),
                  0, &TotalPOT_Dictionary, isa_proxy, 0,
                  sizeof(::TotalPOT) );
      instance.SetNew(&new_TotalPOT);
      instance.SetNewArray(&newArray_TotalPOT);
      instance.SetDelete(&delete_TotalPOT);
      instance.SetDeleteArray(&deleteArray_TotalPOT);
      instance.SetDestructor(&destruct_TotalPOT);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TotalPOT*)
   {
      return GenerateInitInstanceLocal((::TotalPOT*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TotalPOT*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TotalPOT_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::TotalPOT*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_TotalPOT(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TotalPOT : new ::TotalPOT;
   }
   static void *newArray_TotalPOT(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TotalPOT[nElements] : new ::TotalPOT[nElements];
   }
   // Wrapper around operator delete
   static void delete_TotalPOT(void *p) {
      delete ((::TotalPOT*)p);
   }
   static void deleteArray_TotalPOT(void *p) {
      delete [] ((::TotalPOT*)p);
   }
   static void destruct_TotalPOT(void *p) {
      typedef ::TotalPOT current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TotalPOT

/********************************************************
* dict/TotalPOTdict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTotalPOTdict();

extern "C" void G__set_cpp_environmentTotalPOTdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/physics/home/mhogan/software/p0d-banff/p0d-banff/src/TotalPOT.hxx");
  G__cpp_reset_tagtableTotalPOTdict();
}
#include <new>
extern "C" int G__cpp_dllrevTotalPOTdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TotalPOT */
static int G__TotalPOTdict_183_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TotalPOT* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TotalPOT[n];
     } else {
       p = new((void*) gvp) TotalPOT[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TotalPOT;
     } else {
       p = new((void*) gvp) TotalPOT;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOT(*(TString*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun2AirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun2WaterMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun3bAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun3cAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun4AirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun4WaterMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun5cWaterMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6bAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6cAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6dAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6eAirMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun7WaterMC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun2AirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun2WaterData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun3bAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun3cAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun4AirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun4WaterData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun5cWaterData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6bAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6cAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6dAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun6eAirData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTRun7bWaterData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetRun3bAnd3cDataRatio());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTperFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TotalPOTdict_183_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TotalPOT*) G__getstructoffset())->GetPOTperFile_Run6());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TotalPOTdict_183_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TotalPOT* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TotalPOT(*(TotalPOT*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TotalPOT G__TTotalPOT;
static int G__TotalPOTdict_183_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TotalPOT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TotalPOT*) (soff+(sizeof(TotalPOT)*i)))->~G__TTotalPOT();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TotalPOT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TotalPOT*) (soff))->~G__TTotalPOT();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TotalPOTdict_183_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TotalPOT* dest = (TotalPOT*) G__getstructoffset();
   *dest = *(TotalPOT*) libp->para[0].ref;
   const TotalPOT& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TotalPOT */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTotalPOTdict {
 public:
  G__Sizep2memfuncTotalPOTdict(): p(&G__Sizep2memfuncTotalPOTdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTotalPOTdict::*p)();
};

size_t G__get_sizep2memfuncTotalPOTdict()
{
  G__Sizep2memfuncTotalPOTdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTotalPOTdict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTotalPOTdict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TotalPOT */
static void G__setup_memvarTotalPOT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT));
   { TotalPOT *p; p=(TotalPOT*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun2AirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun2WaterMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun3bAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun3cAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun4AirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun4WaterMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun5cWaterMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6bAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6cAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6dAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6eAirMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun7bWaterMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun2AirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun2WaterData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun3bAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun3cAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun4AirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun4WaterData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun5cWaterData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6bAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6cAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6dAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun6eAirData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTRun7bWaterData=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_Run3bAnd3cDataRatio=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTperFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"_POTperFile_Run6=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTotalPOTdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTotalPOT(void) {
   /* TotalPOT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT));
   G__memfunc_setup("TotalPOT",759,G__TotalPOTdict_183_0_1, 105, G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOT",531,G__TotalPOTdict_183_0_2, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "u 'TString' - 11 - runName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun2AirMC",1318,G__TotalPOTdict_183_0_3, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun2WaterMC",1549,G__TotalPOTdict_183_0_4, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun3bAirMC",1417,G__TotalPOTdict_183_0_5, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun3cAirMC",1418,G__TotalPOTdict_183_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun4AirMC",1320,G__TotalPOTdict_183_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun4WaterMC",1551,G__TotalPOTdict_183_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun5cWaterMC",1651,G__TotalPOTdict_183_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6bAirMC",1420,G__TotalPOTdict_183_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6cAirMC",1421,G__TotalPOTdict_183_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6dAirMC",1422,G__TotalPOTdict_183_0_12, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6eAirMC",1423,G__TotalPOTdict_183_0_13, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun7WaterMC",1554,G__TotalPOTdict_183_0_14, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun2AirData",1552,G__TotalPOTdict_183_0_15, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun2WaterData",1783,G__TotalPOTdict_183_0_16, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun3bAirData",1651,G__TotalPOTdict_183_0_17, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun3cAirData",1652,G__TotalPOTdict_183_0_18, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun4AirData",1554,G__TotalPOTdict_183_0_19, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun4WaterData",1785,G__TotalPOTdict_183_0_20, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun5cWaterData",1885,G__TotalPOTdict_183_0_21, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6bAirData",1654,G__TotalPOTdict_183_0_22, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6cAirData",1655,G__TotalPOTdict_183_0_23, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6dAirData",1656,G__TotalPOTdict_183_0_24, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun6eAirData",1657,G__TotalPOTdict_183_0_25, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTRun7bWaterData",1886,G__TotalPOTdict_183_0_26, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRun3bAnd3cDataRatio",2060,G__TotalPOTdict_183_0_27, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTperFile",1242,G__TotalPOTdict_183_0_28, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPOTperFile_Run6",1700,G__TotalPOTdict_183_0_29, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPOT",543,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TotalPOT", 759, G__TotalPOTdict_183_0_31, (int) ('i'), G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT), -1, 0, 1, 1, 1, 0, "u 'TotalPOT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TotalPOT", 885, G__TotalPOTdict_183_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TotalPOTdict_183_0_33, (int) ('u'), G__get_linked_tagnum(&G__TotalPOTdictLN_TotalPOT), -1, 1, 1, 1, 1, 0, "u 'TotalPOT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTotalPOTdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTotalPOTdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTotalPOTdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TotalPOTdictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TotalPOTdictLN_TotalPOT = { "TotalPOT" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTotalPOTdict() {
  G__TotalPOTdictLN_TString.tagnum = -1 ;
  G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TotalPOTdictLN_TotalPOT.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTotalPOTdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_TString);
   G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TotalPOTdictLN_TotalPOT),sizeof(TotalPOT),-1,1280,(char*)NULL,G__setup_memvarTotalPOT,G__setup_memfuncTotalPOT);
}
extern "C" void G__cpp_setupTotalPOTdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTotalPOTdict()");
  G__set_cpp_environmentTotalPOTdict();
  G__cpp_setup_tagtableTotalPOTdict();

  G__cpp_setup_inheritanceTotalPOTdict();

  G__cpp_setup_typetableTotalPOTdict();

  G__cpp_setup_memvarTotalPOTdict();

  G__cpp_setup_memfuncTotalPOTdict();
  G__cpp_setup_globalTotalPOTdict();
  G__cpp_setup_funcTotalPOTdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTotalPOTdict();
  return;
}
class G__cpp_setup_initTotalPOTdict {
  public:
    G__cpp_setup_initTotalPOTdict() { G__add_setup_func("TotalPOTdict",(G__incsetup)(&G__cpp_setupTotalPOTdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTotalPOTdict() { G__remove_setup_func("TotalPOTdict"); }
};
G__cpp_setup_initTotalPOTdict G__cpp_setup_initializerTotalPOTdict;

