/********************************************************************
* dict/TotalPOTdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/TotalPOTdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTotalPOTdict();
extern void G__cpp_setup_inheritanceTotalPOTdict();
extern void G__cpp_setup_typetableTotalPOTdict();
extern void G__cpp_setup_memvarTotalPOTdict();
extern void G__cpp_setup_globalTotalPOTdict();
extern void G__cpp_setup_memfuncTotalPOTdict();
extern void G__cpp_setup_funcTotalPOTdict();
extern void G__set_cpp_environmentTotalPOTdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/physics/home/mhogan/software/p0d-banff/p0d-banff/src/TotalPOT.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TotalPOTdictLN_TString;
extern G__linked_taginfo G__TotalPOTdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TotalPOTdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TotalPOTdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TotalPOTdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TotalPOTdictLN_TotalPOT;

/* STUB derived class for protected member access */
