#!/bin/bash

echo
echo Working on nd280Psyche version v3r26
echo Moving to /physics/home/mhogan/software/t2k-software-clone
cd /physics/home/mhogan/software/t2k-software-clone

cmt co psyche/psychePolicy
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psychePolicy/ | head -1)
echo replacing \'v3r2\' with \'$HEADVERSION\' for psychePolicy in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psychePolicy v3r2 psyche"/"use psychePolicy $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheCore
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheCore/ | head -1)
echo replacing \'v3r22\' with \'$HEADVERSION\' for psycheCore in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheCore v3r22 psyche"/"use psycheCore $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheEventModel
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheEventModel/ | head -1)
echo replacing \'v3r22\' with \'$HEADVERSION\' for psycheEventModel in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheEventModel v3r22 psyche"/"use psycheEventModel $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheUtils
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheUtils/ | head -1)
echo replacing \'v3r22\' with \'$HEADVERSION\' for psycheUtils in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheUtils v3r22 psyche"/"use psycheUtils $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheND280Utils
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheND280Utils/ | head -1)
echo replacing \'v3r24\' with \'$HEADVERSION\' for psycheND280Utils in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheND280Utils v3r24 psyche"/"use psycheND280Utils $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheIO
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheIO/ | head -1)
echo replacing \'v3r18\' with \'$HEADVERSION\' for psycheIO in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheIO v3r18 psyche"/"use psycheIO $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheSelections
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheSelections/ | head -1)
echo replacing \'v3r28\' with \'$HEADVERSION\' for psycheSelections in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheSelections v3r28 psyche"/"use psycheSelections $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheSystematics
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheSystematics/ | head -1)
echo replacing \'v3r24\' with \'$HEADVERSION\' for psycheSystematics in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheSystematics v3r24 psyche"/"use psycheSystematics $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

cmt co psyche/psycheSteering
# change ./requirements replacing the version number with the one just checked out
HEADVERSION=$(ls -t psyche/psycheSteering/ | head -1)
echo replacing \'v3r18\' with \'$HEADVERSION\' for psycheSteering in nd280Psyche/v3r26/cmt/requirements
sed -i -e s/"use psycheSteering v3r18 psyche"/"use psycheSteering $HEADVERSION psyche"/g /physics/home/mhogan/software/t2k-software-clone/nd280Psyche/v3r26/cmt/requirements

